image: python:3.6

stages:
    - codestyle

before_script:
    - pip install pipenv
    - pipenv lock
    - pipenv sync

codestyle:
    stage: codestyle
    script:
        - pipenv run black --check .
        - pipenv run checkdoc
        - pipenv run checktype
